name: Deploy WeMood Backend

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /opt/Wemood_backend
            git pull origin master
            docker compose down
            docker compose up -d --build
            echo "Deployment complete!"
            docker compose ps